### ISSUE TITLE
feature request - add second controller

### ISSUE THREAD

**Issue by micahstubbs** [kfarr/aframe-city-builder#5]
can reproduce the issue in both `54.0a1 (2017-01-29) (64-bit) Firefox Nightly` and `Aug 29 Chromium`
![screenshot 1485732926](https://cloud.githubusercontent.com/assets/2119400/22409050/9a727882-e638-11e6-98f6-cb5188aa0235.jpg)

![screenshot 1485732881](https://cloud.githubusercontent.com/assets/2119400/22409045/892c5700-e638-11e6-9fc4-3f007087aa1b.jpg)

**Comment by micahstubbs** [comment]
ok, got `aframe-city-builder` latest master running locally. 

the `controllerEl` variable is declared, so no more error about that in the console.

**Comment by micahstubbs** [comment]
starting to suspect that the experience might be designed for just one controller :thinking:

**Comment by micahstubbs** [comment]
ok, saw the note in `README.md` about adding a second controller in the future.  count this as a feature request then 😉

**Comment by kfarr** [comment]
I thought I had fixed all those webpack use strict errors, but you found a new one! I just fixed the one you found, but I also updated index.html to ignore the dist build and just reference each js file itself, effectively removing "use strict".

As far as the second controller is concerned, I could add it just as a second object browser and placer, but I'm thinking of adding a "menu" with things like load, save, teleport, etc which might live on that other hand.

**Comment by kfarr** [comment]
Also it seems like it worked in 54.0a1 (2017-01-29) Firefox Nightly but none of the chromiums? It does work for me in Dec 23

**Comment by kfarr** [comment]
Finally, the dev work required to add a second controller is to modify the "aframe-select-bar" component to append a unique name to the ID of elements it generates such that more than one instance of the component can be active on one scene. I'm planning to start that tonight as I need to writeup the component anyway.

**Comment by micahstubbs** [comment]
>  could add it just as a second object browser and placer

as an exercise to learn about the project, I went down this path on a branch this afternoon.  I got both controllers & object menus to render, but the trackpad events to scroll the menu weren't working.

> append a unique name to the ID of elements it generates

good to know!  hadn't figured this out yet. likely just the thing I was missing 😄

**Comment by micahstubbs** [comment]
🎉
